export const SET_SUBTITLE_QUERY = 'SET_SUBTITLE_QUERY';
export const SET_PAGE = 'SET_PAGE';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';
export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS_ERR = 'RECEIVE_SEARCH_RESULTS_ERR';

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const RECEIVE_MOVIE_ERR = 'RECEIVE_MOVIE_ERR';