export const SET_SUBTITLE_QUERY = 'SET_SUBTITLE_QUERY';
export const SET_PAGE = 'SET_PAGE';
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE';

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS = 'RECEIVE_SEARCH_RESULTS';
export const RECEIVE_SEARCH_RESULTS_ERR = 'RECEIVE_SEARCH_RESULTS_ERR';

export const REQUEST_MOVIE = 'REQUEST_MOVIE';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const RECEIVE_MOVIE_ERR = 'RECEIVE_MOVIE_ERR';

export const SET_MOVIE = 'SET_MOVIE';
export const SET_SUBTITLE_RANGE = 'SET_SUBTITLE_RANGE';

export const REQUEST_MOVIE_SUBTITLES = 'REQUEST_MOVIE_SUBTITLES';
export const RECEIVE_MOVIE_SUBTITLES = 'RECEIVE_MOVIE_SUBTITLES';
export const RECEIVE_MOVIE_SUBTITLES_ERR = 'RECEIVE_MOVIE_SUBTITLES_ERR';

export const RENDER_GIF_START= 'RENDER_GIF_START';
export const RECEIVE_GIF_STATUS = 'RECEIVE_GIF_STATUS';