version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "xpack.security.enabled=false"
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - env.list
      - env.secret.list
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=1024MiB
  redis:
    image: redis:alpine
    container_name: redis

  giffer:
    container_name: giffer
    image: giffer:latest
    build:
      context: ../src/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - env.list
      - env.secret.list




volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  pgdata:
    driver: local

networks:
  esnet: